<?php
/**
 * @file
 * Code for the Collabco Wiki Feature feature.
 */

include_once 'off_wiki_feature.features.inc';

/**
 * Implements hook_node_view().
 *
 * Add og_group_ref prepopulate query to 'Add child page' link, so it uses the 
 * parents group by default.
 */
function off_wiki_feature_node_view_alter(&$build) {
  // If this node is connected to a group.
  if (!empty($build['#node']->og_group_ref['und'][0]['target_id'])) {
    // And this is a normal book page.
    if (!empty($build['#node']->book['bid']) && empty($build['#node']->in_preview)) {
      // Put the group idea in the url query for entityreference prepopulate.
      $gid =  $build['#node']->og_group_ref['und'][0]['target_id'];
      $build['links']['book']['#links']['book_add_child']['query']['og_group_ref'] = $gid;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adapted from module new_book_by_default
 */
function off_wiki_feature_form_node_form_alter(&$form, &$form_state, $form_id) {
  // Node is new.
  if (!isset($form['#node']->nid)
      // Content type has/allows a book outline.
      && isset($form['book'])
      // Default is currently <none>.
      && $form['book']['bid']['#default_value'] === 0
      // The <create a new book> option is available.
      && isset($form['book']['bid']['#options']['new'])) {

    // Get options for all content types.
    $content_types_options = variable_get('new_book_by_default_node_types', array('book'));

    // Set default book option to <create a new book>.
    $form['book']['bid']['#default_value'] = 'new';
  }
}

function off_wiki_feature_views_pre_view($view, $display_id, $args) {
  if ($view->name == 'wikis' && $display_id == 'group_page') {
    collabco_groups_feature_view_content_link($view, 'book', 'header');
  }
}

